### ISSUE TITLE
question about paper

### ISSUE THREAD

**Issue by Jiatttliu** [wenbin-lin/RelightableAvatar#1]
Hello, that is a wonderful work!!!
And I have a question about the paper:
You mentioned in the paper that you extract an explicit body mesh by referring to VolSDF and then compute the skinning weights of any vertices. In my opinion, the skinning weights of an explicit mesh are not the same as those of SMPL, so how do you compute them?
Thanks for your reply:>

**Comment by wenbin-lin** [comment]
We use the nearest vertices on the SMPL mesh to compute the skinning weights of the explicit mesh in the canonical space. Implementation details can be found in https://github.com/wenbin-lin/RelightableAvatar/blob/943079a2cdb277d409cca8746bd92660b219b2e4/lib/utils/sample_utils.py#L323

**Comment by Jiatttliu** [comment]
thanks for your reply! I have understood:>

**Comment by Jiatttliu** [comment]
by the way, when I run the code`python train_geometry.py --cfg_file configs/geometry_ps_m3c.yaml exp_name geometry_ps_m3c`, a error occured, how can i solve it ?
```
Traceback (most recent call last):
  File "train_geometry.py", line 107, in <module>
    main()
  File "train_geometry.py", line 94, in main
    train_loader = make_data_loader(cfg,
  File "/data/RelightableAvatar/lib/datasets/make_dataset.py", line 88, in make_data_loader
    dataset = make_dataset(cfg, dataset_name, transforms, is_train)
  File "/data/RelightableAvatar/lib/datasets/make_dataset.py", line 30, in make_dataset
    dataset = _dataset_factory(is_train)
  File "/data/RelightableAvatar/lib/datasets/make_dataset.py", line 25, in _dataset_factory
    dataset = imp.load_source(module, path).Dataset(**args)
  File "lib/datasets/ps_dataset.py", line 52, in __init__
    self.params = np.load(params_path, allow_pickle=True).item()
  File "/opt/conda/envs/RAvatar/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/people_snapshot/male-3-casual/params.npy'
```
This seems to be due to missing files in the dataset, but I downloaded the dataset from the official website

**Comment by wenbin-lin** [comment]
We refer to NeuralBody for processing the PeoplesnapShot dataset.
The missing file "data/people_snapshot/male-3-casual/params.npy" is generated using the script below:
https://github.com/zju3dv/neuralbody/blob/3c516b953477006a3d1a7311eb4d51438c982c33/tools/process_snapshot.py

**Comment by Jiatttliu** [comment]
Sorry I didn't read the README.md carefully and I konw how to do now.
Thanks:)

**Comment by Jiatttliu** [comment]
> by the way, when I run the code`python train_geometry.py --cfg_file configs/geometry_ps_m3c.yaml exp_name geometry_ps_m3c`, a error occured, how can i solve it ?
> 
> ```
> Traceback (most recent call last):
>   File "train_geometry.py", line 107, in <module>
>     main()
>   File "train_geometry.py", line 94, in main
>     train_loader = make_data_loader(cfg,
>   File "/data/RelightableAvatar/lib/datasets/make_dataset.py", line 88, in make_data_loader
>     dataset = make_dataset(cfg, dataset_name, transforms, is_train)
>   File "/data/RelightableAvatar/lib/datasets/make_dataset.py", line 30, in make_dataset
>     dataset = _dataset_factory(is_train)
>   File "/data/RelightableAvatar/lib/datasets/make_dataset.py", line 25, in _dataset_factory
>     dataset = imp.load_source(module, path).Dataset(**args)
>   File "lib/datasets/ps_dataset.py", line 52, in __init__
>     self.params = np.load(params_path, allow_pickle=True).item()
>   File "/opt/conda/envs/RAvatar/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
>     fid = stack.enter_context(open(os_fspath(file), "rb"))
> FileNotFoundError: [Errno 2] No such file or directory: 'data/people_snapshot/male-3-casual/params.npy'
> ```
> 
> This seems to be due to missing files in the dataset, but I downloaded the dataset from the official website

hello, another question.
The script `process_snapshot.py` provided by neuralbody doesn't seem to generate the `*.npy` files in the `lbs` folder because it doesn't need the data anymore, but you do need it for this work. Could you please provide a link to download the missing files?thanks!

**Comment by wenbin-lin** [comment]
Sorry, I will provide a new script to generate the missing files soon.

**Comment by Jiatttliu** [comment]
It doesn't matter. Waiting for your update:)

**Comment by wenbin-lin** [comment]
The script for processing the Peoplesnapshot dataset is updated.
https://github.com/wenbin-lin/RelightableAvatar/blob/39d0522f4f49230d32b3c5d8a7c1c7e2625d3a6c/process_snapshot.py
