### ISSUE TITLE
question in 'lib/networks/render/mat_render.py'

### ISSUE THREAD

**Issue by Jiatttliu** [wenbin-lin/RelightableAvatar#3]
There is a method called 'get_mesh_v_tbw' in the 'lib/networks/render/mat_render.py'. I don't understand this method. It seems to transform coordinates between canonical space and observation space again and again and I am refused. Can you explain it?
By the way, Is the physics-based rendering process in line 355 of [file](https://github.com/wenbin-lin/RelightableAvatar/tree/main/lib/networks)?
` color_sg_ret = self.color_sg_network(wpts, gradients, viewdir, posed_pts, j_transform, poses, rot_w2big)
`

**Comment by wenbin-lin** [comment]
The 'get_mesh_v_tbw' function  is used to compute the skinning weights of the explicit mesh. The mesh skinning weights are computed in the canonical space with the neural non-rigid deformation applied. Then we transform the explicit mesh to the world coordinates, so we can use the skinning weights of mesh vertices to compute the inverse skinning weights of ray points in the world coordinates.

Yes, the physics-based rendering process is done in the ColorSGNetwork module.
